# Generated by Django 5.1.2 on 2024-10-30 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="consumptions",
            options={
                "verbose_name": "Подсчёт расходов",
                "verbose_name_plural": "Подсчёты расходов",
            },
        ),
        migrations.AlterModelOptions(
            name="others",
            options={
                "verbose_name": "Прочие расходы",
                "verbose_name_plural": "Прочие расходы",
            },
        ),
        migrations.AlterModelOptions(
            name="ownpr",
            options={
                "verbose_name": "Себестоимость",
                "verbose_name_plural": "Себестоимости",
            },
        ),
        migrations.AlterModelOptions(
            name="subcons",
            options={
                "verbose_name": "Часть расхода",
                "verbose_name_plural": "Части расхода",
            },
        ),
        migrations.AddField(
            model_name="ownpr",
            name="name",
            field=models.CharField(
                max_length=150, null=True, verbose_name="Наименование товара"
            ),
        ),
    ]
