# Generated by Django 5.1.2 on 2024-10-30 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_consumptions_options_alter_others_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subcons",
            name="name",
            field=models.CharField(
                max_length=70, null=True, verbose_name="Наименование расхода"
            ),
        ),
    ]
